[project]
name = "backtester"
version = "0.1.0"
dependencies = [
    "alpaca>=1.0.0",
    "alpaca-py>=0.42.1",
    "alpaca-trade-api>=3.2.0",
    "backtesting>=0.6.5",
    "dotenv>=0.9.9",
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
    "yfinance>=0.2.58",
]
